In [50]:
import pandas as pd
import numpy as np
import math

In [51]:
ls

bayes.ipynb                main.py        SupportVectorMachine.ipynb
data_preprocessing.ipynb   Model.py       svm.ipynb
logistic.ipynb             __pycache__/   temporaryFile.ipynb
logistic_regression.ipynb  spambase/
LrSvmBaysian.ipynb         spambase.data


In [52]:
d = 58 # 57 input attributes + 1 target label

labels = ['f' + str(i) for i in range(1, d)]
labels.append('t')

labels

['f1',
 'f2',
 'f3',
 'f4',
 'f5',
 'f6',
 'f7',
 'f8',
 'f9',
 'f10',
 'f11',
 'f12',
 'f13',
 'f14',
 'f15',
 'f16',
 'f17',
 'f18',
 'f19',
 'f20',
 'f21',
 'f22',
 'f23',
 'f24',
 'f25',
 'f26',
 'f27',
 'f28',
 'f29',
 'f30',
 'f31',
 'f32',
 'f33',
 'f34',
 'f35',
 'f36',
 'f37',
 'f38',
 'f39',
 'f40',
 'f41',
 'f42',
 'f43',
 'f44',
 'f45',
 'f46',
 'f47',
 'f48',
 'f49',
 'f50',
 'f51',
 'f52',
 'f53',
 'f54',
 'f55',
 'f56',
 'f57',
 't']

In [53]:
data = pd.read_csv('spambase.data', header = None)

data.columns = labels

In [54]:
data.head(10)

f1    f2    f3   f4    f5    f6    f7    f8    f9   f10  ...   f49  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.00   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.00   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.01   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
5  0.00  0.00  0.00  0.0  1.85  0.00  0.00  1.85  0.00  0.00  ...  0.00   
6  0.00  0.00  0.00  0.0  1.92  0.00  0.00  0.00  0.00  0.64  ...  0.00   
7  0.00  0.00  0.00  0.0  1.88  0.00  0.00  1.88  0.00  0.00  ...  0.00   
8  0.15  0.00  0.46  0.0  0.61  0.00  0.30  0.00  0.92  0.76  ...  0.00   
9  0.06  0.12  0.77  0.0  0.19  0.32  0.38  0.00  0.06  0.00  ...  0.04   

     f50  f51    f52    f53    f54    f55  f56   f57  t  
0  0.000  0.0  0.778  0.000  0.000  3.756   61   278  1  
1  0.132  0.0  0.372  0.180  0.048  5.114  101  1028  1  
2  0.143  0.0  0.276  0.184  0.010  9.821  485  2259  1  
3  0.137  0.0  0.137  0.000  0.000  3.537   40   191  1  
4  0.135  0.0  0.135  0.000  0.000  3.537   40   191  1  
5  0.223  0.0  0.000  0.000  0.000  3.000   15    54  1  
6  0.054  0.0  0.164  0.054  0.000  1.671    4   112  1  
7  0.206  0.0  0.000  0.000  0.000  2.450   11    49  1  
8  0.271  0.0  0.181  0.203  0.022  9.744  445  1257  1  
9  0.030  0.0  0.244  0.081  0.000  1.729   43   749  1  

[10 rows x 58 columns]

In [55]:
target = data['t']
# target = pd.DataFrame(data['t'], columns = ['t'])
data = data.drop(columns = 't')
d -= 1

In [56]:
data.head(10)

f1    f2    f3   f4    f5    f6    f7    f8    f9   f10  ...  f48   f49  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.0  0.00   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.0  0.00   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.0  0.01   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.0  0.00   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.0  0.00   
5  0.00  0.00  0.00  0.0  1.85  0.00  0.00  1.85  0.00  0.00  ...  0.0  0.00   
6  0.00  0.00  0.00  0.0  1.92  0.00  0.00  0.00  0.00  0.64  ...  0.0  0.00   
7  0.00  0.00  0.00  0.0  1.88  0.00  0.00  1.88  0.00  0.00  ...  0.0  0.00   
8  0.15  0.00  0.46  0.0  0.61  0.00  0.30  0.00  0.92  0.76  ...  0.0  0.00   
9  0.06  0.12  0.77  0.0  0.19  0.32  0.38  0.00  0.06  0.00  ...  0.0  0.04   

     f50  f51    f52    f53    f54    f55  f56   f57  
0  0.000  0.0  0.778  0.000  0.000  3.756   61   278  
1  0.132  0.0  0.372  0.180  0.048  5.114  101  1028  
2  0.143  0.0  0.276  0.184  0.010  9.821  485  2259  
3  0.137  0.0  0.137  0.000  0.000  3.537   40   191  
4  0.135  0.0  0.135  0.000  0.000  3.537   40   191  
5  0.223  0.0  0.000  0.000  0.000  3.000   15    54  
6  0.054  0.0  0.164  0.054  0.000  1.671    4   112  
7  0.206  0.0  0.000  0.000  0.000  2.450   11    49  
8  0.271  0.0  0.181  0.203  0.022  9.744  445  1257  
9  0.030  0.0  0.244  0.081  0.000  1.729   43   749  

[10 rows x 57 columns]

In [57]:
target.head(10)

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: t, dtype: int64

In [58]:
# Binning (to handle real valued features for computing conditional probs.)

no_of_bins = 30
bins = np.zeros((no_of_bins, d))# 2 * d)) # row1 - min and row2 - max

for i in range(0, d):
    col_label = 'f' + str(i+1)
    column = data[col_label]
    
    # finding max and min in each column for binning
    min = max = column[0]
    for j in range(1, len(column)):
        if column[j] < min:
            min = column[j]
        if column[j] > max:
            max = column[j]        
    
    # splitting range into 20 bins
    d = (max - min) / (no_of_bins)
    for j in range(0, no_of_bins):
        bins[j, i] = min + j * d
#         bins[j, 2*i] = min + j * d
#         bins[j, 2*i + 1] = min + (j+1) * d

In [59]:
bins

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.51333333e-01, 4.76000000e-01, 1.70000000e-01, ...,
        3.77166667e+01, 3.33933333e+02, 5.29000000e+02],
       [3.02666667e-01, 9.52000000e-01, 3.40000000e-01, ...,
        7.44333333e+01, 6.66866667e+02, 1.05700000e+03],
       ...,
       [4.08600000e+00, 1.28520000e+01, 4.59000000e+00, ...,
        9.92350000e+02, 8.99020000e+03, 1.42570000e+04],
       [4.23733333e+00, 1.33280000e+01, 4.76000000e+00, ...,
        1.02906667e+03, 9.32313333e+03, 1.47850000e+04],
       [4.38866667e+00, 1.38040000e+01, 4.93000000e+00, ...,
        1.06578333e+03, 9.65606667e+03, 1.53130000e+04]])

In [60]:
def find_bin(val, feature):
    bin = 0
    for i in range(0, no_of_bins):
        if val > bins[i, feature]:
            bin = i
    return bin       

In [61]:
# relabelling the feature values (Binnning)

for i in range(0, data.shape[1]):
    col_label = 'f' + str(i+1)
    for j in range(0, data.shape[0]):
        data.loc[j, col_label] = int(find_bin(data.loc[j, col_label], i))

In [62]:
data

f1   f2   f3   f4   f5   f6   f7   f8   f9  f10  ...  f48  f49  f50  \
0     0.0  1.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     1.0  0.0  2.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
2     0.0  0.0  4.0  0.0  3.0  0.0  0.0  0.0  3.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
4596  2.0  0.0  3.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4597  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4598  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  2.0   
4599  6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4600  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      f51  f52  f53  f54  f55  f56  f57  
0     0.0  0.0  0.0  0.0  0.0    0    0  
1     0.0  0.0  0.0  0.0  0.0    0    1  
2     0.0  0.0  0.0  0.0  0.0    1    4  
3     0.0  0.0  0.0  0.0  0.0    0    0  
4     0.0  0.0  0.0  0.0  0.0    0    0  
...   ...  ...  ...  ...  ...  ...  ...  
4596  0.0  0.0  0.0  0.0  0.0    0    0  
4597  0.0  0.0  0.0  0.0  0.0    0    0  
4598  0.0  0.0  0.0  0.0  0.0    0    0  
4599  0.0  0.0  0.0  0.0  0.0    0    0  
4600  0.0  0.0  0.0  0.0  0.0    0    0  

[4601 rows x 57 columns]

In [63]:
# relabeling targets .ie. {1 - spam, 0 - not spam} (old) ----> {1,-1} (new)

new_target = target

for i in range(0, len(new_target)):
    if new_target[i] == 1:
        new_target[i] = 1
    else:
        new_target[i] = 0

target = pd.DataFrame(new_target, columns = ['t'])

# new_target = []

# for val in target['t']:
#     if val == 1:
#         new_target.append(1)
#     else:
#         new_target.append(-1)

# target = pd.DataFrame(new_target, columns = ['t'])

In [64]:
target.head(10)

t
0  1
1  1
2  1
3  1
4  1
5  1
6  1
7  1
8  1
9  1

In [65]:
target['t'].unique()

array([1, 0])

In [66]:
import math, random

def train_test_split(X, y, f):
    # f : fraction of samples taken for training; in the range (0,1)
    n = X.shape[0]
    m = math.floor(f * n)
    row_indices = [i for i in range(0, X.shape[0])]

    random.shuffle(row_indices)
    test_rows = row_indices[0:n-m]

    train_rows = [i for i in range(0, m)]
    
    X_test = pd.DataFrame(columns = labels[0:len(labels)-1])
    y_test = pd.DataFrame(columns = ['t'])
    
    for row in test_rows:
        X_test.loc[len(X_test)] = X.iloc[row]
        y_test.loc[len(y_test)] = y.iloc[row]
    
    X_train = pd.DataFrame(X.drop(X.index[test_rows]))
    y_train = pd.DataFrame(y.drop(y.index[test_rows]))
    
    return X_train, X_test, y_train, y_test

In [67]:
X_train, X_test, y_train, y_test = train_test_split(data, target, 0.9)

In [68]:
X_train.shape

(4140, 57)

In [69]:
X_test.shape

(461, 57)

In [70]:
y_train.shape

(4140, 1)

In [71]:
y_test.shape

(461, 1)

In [72]:
import random
import numpy as np

In [73]:
def compute_prob_y():
    prob_1 = 0
    prob_0 = 0
    for i in range(0, X_train.shape[0]):
        if target.loc[i, 't'] == 1:
            prob_1 += 1
        else:
            prob_0 += 1
            
    prob_1 /= (X_train.shape[0] + 0.0)
    prob_0 /= (X_train.shape[0] + 0.0)
#     print("prob one : ", p_1)
#     print("prob zero : ", p_0)
    return prob_1, prob_0
   
prob_1, prob_0 = compute_prob_y()

In [74]:
prob_0

0.5620772946859903

In [75]:
prob_1

0.4379227053140097

In [76]:
def compute_prob_x_given_1():
    prob_x_given_1 = np.zeros((no_of_bins, X_train.shape[1]))

    for i in range(0, X_train.shape[0]):
        for j in range(0, X_train.shape[1]):
            x_val = int(data.loc[i, 'f' + str(j+1)])
            y_val = target.loc[i, 't']
            if y_val == 1:
                prob_x_given_1[x_val, j] += (1.0 / (prob_1 * X_train.shape[0]))
                
    return prob_x_given_1

prob_x_given_1 = compute_prob_x_given_1()

In [77]:
prob_x_given_1

array([[7.32487590e-01, 8.77551020e-01, 4.20849421e-01, ...,
        9.75179261e-01, 9.28847215e-01, 7.49034749e-01],
       [6.89464975e-02, 9.32156646e-02, 1.18587976e-01, ...,
        1.10314396e-02, 3.41974628e-02, 1.32377275e-01],
       [6.56370656e-02, 1.70987314e-02, 1.19691120e-01, ...,
        4.96414782e-03, 2.64754550e-02, 6.67402096e-02],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.51571980e-04, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.51571980e-04, 0.00000000e+00, 0.00000000e+00, ...,
        5.51571980e-04, 5.51571980e-04, 5.51571980e-04]])

In [78]:
def compute_prob_x_given_0():
    prob_x_given_0 = np.zeros((no_of_bins, X_train.shape[1]))

    for i in range(0, X_train.shape[0]):
        for j in range(0, X_train.shape[1]):
            x_val = int(data.loc[i, 'f' + str(j+1)])
            y_val = target.loc[i, 't']
            if y_val == 0:
                prob_x_given_0[x_val, j] += (1.0 / (prob_0 * X_train.shape[0]))
                
    return prob_x_given_0

prob_x_given_0 = compute_prob_x_given_0() 

In [79]:
prob_x_given_0

array([[9.05887409e-01, 9.59604641e-01, 7.88568973e-01, ...,
        9.99140524e-01, 9.98710786e-01, 9.15771379e-01],
       [3.00816502e-02, 8.16501934e-03, 6.27417275e-02, ...,
        4.29737860e-04, 8.59475720e-04, 5.45767082e-02],
       [1.76192523e-02, 7.30554362e-03, 3.43790288e-02, ...,
        0.00000000e+00, 0.00000000e+00, 1.54705630e-02],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.50408251e-02, 4.29737860e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [80]:
def predict(x):
    prob_1_given_x = prob_1
    for i in range(0, X_train.shape[1]):
        x_i = int(x[i])
        prob_1_given_x *= prob_x_given_1[x_i, i]
    prob_0_given_x = prob_0
    for i in range(0, X_train.shape[1]):
        x_i = int(x[i])
        prob_0_given_x *= prob_x_given_0[x_i, i]
    
    if prob_0_given_x < prob_1_given_x:
        pred = 1
    else:
        pred = 0
    return pred      

In [81]:
# Accuracy = # correct predictions / # predictions

correct_preds = 0

for i in range(0, X_test.shape[0]):
    x = X_test.iloc[i]
    if predict(x) == y_test.loc[i, 't']:
        correct_preds += 1

accuracy = correct_preds / (X_test.shape[0] + 0.0)        

In [82]:
accuracy

0.911062906724512